name: Publish Artifacts

on:
  release:
    types:
      - published

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 17
          cache: 'gradle'
      - name: Grant execute permission to gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - uses: Kir-Antipov/mc-publish@v3.1
        with:
          files-primary: build/libs/!(*-@(dev|sources|api)).jar
          modrinth-files-secondary: build/libs/*-@(sources).jar
          github-files-secondary: build/libs/*-@(dev|sources|api).jar
          version-type: release
          version-resolver: releases
          modrinth-featured: true
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          retry-attempts: 2
          retry-delay: 10000
          fail-mode: skip
